import { useEffect, useMemo, useState } from 'react';
import { Edit3, Tags } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { DeleteButton, EmptyState, Modal, PageIntro, Toolbar } from '../components/AdminUI';

interface Project { id: string; title: string }
interface Feature { id: string; project_id: string; feature: string; sort_order: number }
const blank = { id: '', project_id: '', feature: '', sort_order: 0 };

export default function ProjectFeaturesPage() {
  const [rows, setRows] = useState<Feature[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [form, setForm] = useState(blank); const [open, setOpen] = useState(false); const [search, setSearch] = useState(''); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); const [f, p] = await Promise.all([supabase.from('project_features').select('*').order('sort_order'), supabase.from('projects').select('id,title').order('title')]); if (f.error) setError(f.error.message); setRows(f.data ?? []); setProjects(p.data ?? []); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const lookup = Object.fromEntries(projects.map(p => [p.id, p.title]));
  const filtered = useMemo(() => rows.filter(r => `${r.feature} ${lookup[r.project_id] ?? r.project_id}`.toLowerCase().includes(search.toLowerCase())), [rows, search, lookup]);
  const edit = (r?: Feature) => { setForm(r ? { ...r } : { ...blank, project_id: projects[0]?.id ?? '' }); setOpen(true); setError(''); };
  const save = async () => { setSaving(true); const payload = { project_id: form.project_id, feature: form.feature, sort_order: Number(form.sort_order) || 0 }; const res = form.id ? await supabase.from('project_features').update(payload).eq('id', form.id) : await supabase.from('project_features').insert(payload); if (res.error) setError(res.error.message); else { setOpen(false); await load(); } setSaving(false); };
  const remove = async (id: string) => { if (!confirm('Delete this feature?')) return; const res = await supabase.from('project_features').delete().eq('id', id); if (res.error) setError(res.error.message); else await load(); };
  return <div className="admin-page-stack"><PageIntro title="Project Features" description="Manage the feature rows connected to each project." onAdd={() => edit()} addLabel="New Feature" /><Toolbar search={search} setSearch={setSearch} onRefresh={load} />{error && <div className="admin-alert error">{error}</div>}<section className="admin-table-panel"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Feature</th><th>Project</th><th>Sort</th><th>Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={4}><div className="admin-loading-row" /></td></tr> : filtered.length === 0 ? <tr><td colSpan={4}><EmptyState text="No feature records found." /></td></tr> : filtered.map(r => <tr key={r.id}><td><div className="admin-cell-title"><div className="admin-thumb violet"><Tags size={16} /></div><div><strong>{r.feature}</strong><span>ID: {r.id}</span></div></div></td><td><span className="admin-tag">{lookup[r.project_id] ?? r.project_id}</span></td><td>{r.sort_order}</td><td><div className="admin-actions"><button className="admin-row-icon" onClick={() => edit(r)}><Edit3 size={16} /></button><DeleteButton onClick={() => remove(r.id)} /></div></td></tr>)}</tbody></table></div></section><Modal open={open} title={form.id ? 'Edit Feature' : 'Create Feature'} onClose={() => setOpen(false)} onSave={() => void save()} saving={saving}><div className="admin-form-grid"><label className="admin-field full">Project<select value={form.project_id} onChange={e => setForm({ ...form, project_id: e.target.value })}>{projects.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label className="admin-field full">Feature<textarea rows={4} value={form.feature} onChange={e => setForm({ ...form, feature: e.target.value })} /></label><label className="admin-field">Sort order<input type="number" value={form.sort_order} onChange={e => setForm({ ...form, sort_order: Number(e.target.value) })} /></label></div></Modal></div>;
}
